# Generated by Django 4.2.27 on 2026-08-25 21:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('code_gen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSequenceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('name', models.CharField(default='default', max_length=50, unique=True, verbose_name='Sequence name')),
                ('counter', models.PositiveBigIntegerField(default=0, verbose_name='Internal counter')),
            ],
            options={
                'verbose_name': 'Code Sequence',
                'verbose_name_plural': 'Code Sequences',
                'db_table': 'apps_code_gen_sequence',
            },
        ),
        migrations.CreateModel(
            name='StampLayoutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Layout name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_default', models.BooleanField(default=False, verbose_name='Use as default layout')),
            ],
            options={
                'verbose_name': 'Stamp Layout',
                'verbose_name_plural': 'Stamp Layouts',
                'db_table': 'apps_code_gen_stamp_layout',
            },
        ),
        migrations.AddField(
            model_name='coderegistrationmodel',
            name='generated_barcode',
            field=models.BooleanField(default=False, verbose_name='Barcode generated'),
        ),
        migrations.AddField(
            model_name='coderegistrationmodel',
            name='generated_qr',
            field=models.BooleanField(default=False, verbose_name='QR generated'),
        ),
        migrations.AddField(
            model_name='coderegistrationmodel',
            name='hash_fragment',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Hash fragment (base64)'),
        ),
        migrations.AddField(
            model_name='coderegistrationmodel',
            name='initials',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Certificate initials'),
        ),
        migrations.AddField(
            model_name='coderegistrationmodel',
            name='qr_payload',
            field=models.TextField(blank=True, null=True, verbose_name='QR payload'),
        ),
        migrations.AddField(
            model_name='coderegistrationmodel',
            name='random_code',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='Unique random code'),
        ),
        migrations.AddField(
            model_name='coderegistrationmodel',
            name='sequence',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Autonomous sequence'),
        ),
        migrations.AddField(
            model_name='coderegistrationmodel',
            name='source_file_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='Source file hash (SHA-256)'),
        ),
        migrations.CreateModel(
            name='StampPlacementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('kind', models.CharField(choices=[('BARCODE', 'Barcode (Code128)'), ('QR', 'QR code')], default='QR', max_length=10, verbose_name='Code kind')),
                ('page_selector', models.CharField(choices=[('FIRST', 'First page'), ('LAST', 'Last page'), ('ALL', 'Every page'), ('NUMBERS', 'Specific pages')], default='LAST', max_length=10, verbose_name='Pages')),
                ('page_numbers', models.CharField(blank=True, help_text='Comma separated, 1-based. Only used with the specific pages selector.', max_length=100, null=True, verbose_name='Page numbers')),
                ('anchor', models.CharField(choices=[('BL', 'Bottom left'), ('BC', 'Bottom center'), ('BR', 'Bottom right'), ('TL', 'Top left'), ('TC', 'Top center'), ('TR', 'Top right')], default='BR', max_length=2, verbose_name='Anchor')),
                ('offset_x', models.FloatField(default=28.0, verbose_name='Horizontal offset (pt)')),
                ('offset_y', models.FloatField(default=28.0, verbose_name='Vertical offset (pt)')),
                ('width', models.FloatField(default=84.0, validators=[django.core.validators.MinValueValidator(1.0)], verbose_name='Width (pt)')),
                ('height', models.FloatField(default=84.0, validators=[django.core.validators.MinValueValidator(1.0)], verbose_name='Height (pt)')),
                ('opacity', models.FloatField(default=1.0, verbose_name='Opacity')),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='code_gen.stamplayoutmodel', verbose_name='Layout')),
            ],
            options={
                'verbose_name': 'Stamp Placement',
                'verbose_name_plural': 'Stamp Placements',
                'db_table': 'apps_code_gen_stamp_placement',
                'ordering': ['default_order', 'id'],
            },
        ),
    ]
