# Generated by Django 4.2.27 on 2026-08-28 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0005_alter_documentverificationmodel_delivery_method_and_more'),
        ('code_gen', '0003_default_stamp_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='coderegistrationmodel',
            name='document',
            field=models.ForeignKey(blank=True, help_text='Set when the code was issued as part of certifying a document.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='code_registrations', to='certificates.documentverificationmodel', verbose_name='Certified document'),
        ),
    ]
