# Generated by Django 4.2.27 on 2026-08-29 04:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0006_aegissummarydocumentmodel_aegissummarymodel_and_more'),
        ('code_gen', '0004_coderegistrationmodel_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationAnchorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('anchor_type', models.CharField(choices=[('RFC3161', 'Timestamp authority (RFC 3161)'), ('OTS', 'OpenTimestamps (Bitcoin)')], max_length=20, verbose_name='Anchor type')),
                ('payload_hash', models.CharField(db_index=True, help_text='The master hash at the moment it was anchored.', max_length=64, verbose_name='Anchored hash')),
                ('status', models.CharField(choices=[('PENDING', 'Pending confirmation'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20, verbose_name='Status')),
                ('proof', models.BinaryField(blank=True, help_text='DER timestamp token, or the .ots proof file.', null=True, verbose_name='Proof')),
                ('provider', models.CharField(blank=True, default='', max_length=255, verbose_name='Provider')),
                ('stamped_at', models.DateTimeField(blank=True, help_text='The time the anchor itself attests, not our clock.', null=True, verbose_name='Attested time')),
                ('serial', models.CharField(blank=True, default='', max_length=80, verbose_name='Serial')),
                ('detail', models.TextField(blank=True, default='', verbose_name='Detail')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anchors', to='certificates.aegissummarymodel', verbose_name='Summary')),
            ],
            options={
                'verbose_name': 'Certification anchor',
                'verbose_name_plural': 'Certification anchors',
                'db_table': 'apps_code_gen_certification_anchor',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['payload_hash'], name='apps_code_g_payload_e8a3ce_idx'), models.Index(fields=['anchor_type', 'status'], name='apps_code_g_anchor__47ef2e_idx')],
            },
        ),
    ]
