# Generated by Django 4.2.27 on 2026-08-29 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_gen', '0005_certificationanchormodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='stampplacementmodel',
            name='member_code',
            field=models.CharField(blank=True, default='', help_text='Only for the member barcode: which document of the box this position carries (AEGIS-1, AEGIS-2…).', max_length=30, verbose_name='Member code'),
        ),
        migrations.AlterField(
            model_name='stampplacementmodel',
            name='kind',
            field=models.CharField(choices=[('BARCODE', 'Barcode (Code128)'), ('QR', 'QR code'), ('MEMBER', 'Member barcode (summary only)'), ('ANCHOR', 'Anchor QR (summary only)')], default='QR', max_length=10, verbose_name='Code kind'),
        ),
    ]
