# Generated by Django 4.2.27 on 2026-08-31 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("code_gen", "0006_stampplacementmodel_member_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stampplacementmodel",
            name="member_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Only for the member barcode: which document of the summary this position carries (AEGIS-1, AEGIS-2…).",
                max_length=30,
                verbose_name="Member code",
            ),
        ),
    ]
