# Generated by Django 5.2.17 on 2026-09-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("code_gen", "0007_alter_stampplacementmodel_member_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="coderegistrationmodel",
            name="qr_logo_image",
            field=models.ImageField(
                blank=True,
                help_text='Only used when the QR logo is set to "Custom image".',
                null=True,
                upload_to="code_gen/qr_logos/",
                verbose_name="Custom QR logo image",
            ),
        ),
        migrations.AddField(
            model_name="coderegistrationmodel",
            name="qr_logo_mode",
            field=models.CharField(
                choices=[
                    ("DEFAULT", "GEA institutional logo (default)"),
                    ("NONE", "No logo"),
                    ("CUSTOM", "Custom image"),
                ],
                default="DEFAULT",
                max_length=10,
                verbose_name="QR logo",
            ),
        ),
    ]
