# Generated by Django 4.2.21 on 2025-09-15 19:37

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfferModel',
            fields=[
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('offer_type', models.CharField(choices=[('O', 'Official purchase of the United States')], default='O', max_length=255, verbose_name='Purchase order Type')),
                ('quantity_type', models.CharField(choices=[('U', 'Units'), ('B', 'Boxes')], default='B', max_length=255, verbose_name='quantity type')),
                ('offer_quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity needed')),
                ('en_observation', models.TextField(blank=True, null=True, verbose_name='Observation (EN)')),
                ('es_observation', models.TextField(blank=True, null=True, verbose_name='Observation (ES)')),
                ('en_description', models.TextField(blank=True, null=True, verbose_name='Description (EN)')),
                ('es_description', models.TextField(blank=True, null=True, verbose_name='Description (ES)')),
                ('display', models.BooleanField(default=True, verbose_name='Display')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('approved_by_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Approved By Timestamp')),
                ('reviewed', models.BooleanField(default=False, verbose_name='Reviewed')),
                ('reviewed_by_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed By Timestamp')),
                ('service_order_created_at', models.DateTimeField(blank=True, null=True, verbose_name='Service Order Created At')),
                ('service_order_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Service Order Sent At')),
                ('payment_order_created_at', models.DateTimeField(blank=True, null=True, verbose_name='Payment Order Created At')),
                ('payment_order_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Payment Order Sent At')),
                ('asset_in_possession_at', models.DateTimeField(blank=True, null=True, verbose_name='Asset In Possession At')),
                ('asset_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Asset Sent At')),
                ('profitability_created_at', models.DateTimeField(blank=True, null=True, verbose_name='Profitability Created At')),
                ('profitability_paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Profitability Paid At')),
                ('recovery_repatriation_foundation_paid', models.BooleanField(default=False)),
                ('recovery_repatriation_foundation_mark_at', models.DateTimeField(blank=True, null=True)),
                ('am_pro_service_paid', models.BooleanField(default=False)),
                ('am_pro_service_mark_at', models.DateTimeField(blank=True, null=True)),
                ('propensiones_paid', models.BooleanField(default=False)),
                ('propensiones_mark_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Purchase order',
                'verbose_name_plural': 'Purchase orders',
                'db_table': 'apps_buyers_offer',
                'ordering': ['default_order', '-created'],
                'permissions': [('can_approve_offer', 'Can approve purchase orders'), ('can_review_offer', 'Can review purchase orders'), ('can_send_service_order', 'Can send service orders'), ('can_create_payment_order', 'Can create payment orders'), ('can_send_payment_order', 'Can send payment orders'), ('can_set_asset_possession', 'Can set asset in possession'), ('can_send_asset', 'Can send asset'), ('can_set_profitability', 'Can set profitability'), ('can_pay_profitability', 'Can pay profitability'), ('can_see_profitability_page', 'Can see profitability page')],
            },
        ),
        migrations.CreateModel(
            name='ServiceOrderRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('user_type', models.CharField(blank=True, choices=[('I', 'Intermediary'), ('R', 'Representative'), ('H', 'Holder'), ('B', 'Buyer')], max_length=2, null=True)),
            ],
            options={
                'verbose_name': 'Service Order Recipient',
                'verbose_name_plural': 'Service Order Recipients',
                'db_table': 'apps_buyers_service_order_recipient',
                'ordering': ['default_order', '-created'],
            },
        ),
    ]
