# Generated by Django 4.2.21 on 2025-09-08 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('assets_location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferModel',
            fields=[
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('offer_type', models.CharField(choices=[('O', 'Official purchase of the United States')], default='O', max_length=255, verbose_name='Purchase order Type')),
                ('quantity_type', models.CharField(choices=[('U', 'Units'), ('B', 'Boxes')], default='B', max_length=255, verbose_name='quantity type')),
                ('offer_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Total value of the offer ($ USD)')),
                ('offer_quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity needed')),
                ('en_observation', models.TextField(blank=True, null=True, verbose_name='Observation (EN)')),
                ('es_observation', models.TextField(blank=True, null=True, verbose_name='Observation (ES)')),
                ('en_description', models.TextField(blank=True, null=True, verbose_name='Description (EN)')),
                ('es_description', models.TextField(blank=True, null=True, verbose_name='Description (ES)')),
                ('display', models.BooleanField(default=True, verbose_name='Display')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('approved_by_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Approved By Timestamp')),
                ('reviewed', models.BooleanField(default=False, verbose_name='Reviewed')),
                ('reviewed_by_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed By Timestamp')),
                ('service_order_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Service Order Sent At')),
                ('payment_order_created_at', models.DateTimeField(blank=True, null=True, verbose_name='Payment Order Created At')),
                ('payment_order_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Payment Order Sent At')),
                ('asset_in_possession_at', models.DateTimeField(blank=True, null=True, verbose_name='Asset In Possession At')),
                ('asset_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Asset Sent At')),
                ('profitability_created_at', models.DateTimeField(blank=True, null=True, verbose_name='Profitability Created At')),
                ('profitability_paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Profitability Paid At')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyers_offer_approved_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyers_offer_asset', to='assets.assetmodel', verbose_name='Asset')),
                ('asset_in_possession_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyers_offer_asset_in_possession_by', to=settings.AUTH_USER_MODEL, verbose_name='Asset In Possession By')),
                ('asset_sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyers_offer_asset_sent_by', to=settings.AUTH_USER_MODEL, verbose_name='Asset Sent By')),
                ('buyer_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyers_offer_country', to='assets_location.assetcountrymodel', verbose_name='Country')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyers_offer_user', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('payment_order_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyers_offer_payment_order_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Payment Order Created By')),
                ('payment_order_sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyers_offer_payment_order_sent_by', to=settings.AUTH_USER_MODEL, verbose_name='Payment Order Sent By')),
                ('profitability_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyers_offer_profitability_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Profitability Created By')),
                ('profitability_paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyers_offer_profitability_paid_by', to=settings.AUTH_USER_MODEL, verbose_name='Profitability Paid By')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyers_offer_reviewed_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
                ('service_order_sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyers_offer_service_order_sent_by', to=settings.AUTH_USER_MODEL, verbose_name='Service Order Sent By')),
            ],
            options={
                'verbose_name': '1. Purchase order',
                'verbose_name_plural': '1. Purchase orders',
                'db_table': 'apps_buyers_offer',
                'ordering': ['default_order', '-created'],
                'permissions': [('can_approve_offer', 'Can approve purchase orders'), ('can_review_offer', 'Can review purchase orders'), ('can_send_service_order', 'Can send service orders'), ('can_create_payment_order', 'Can create payment orders'), ('can_send_payment_order', 'Can send payment orders'), ('can_set_asset_possession', 'Can set asset in possession'), ('can_send_asset', 'Can send asset'), ('can_set_profitability', 'Can set profitability'), ('can_pay_profitability', 'Can pay profitability')],
            },
        ),
    ]
