# Generated by Django 4.2.21 on 2025-08-28 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offermodel',
            name='en_banner',
        ),
        migrations.RemoveField(
            model_name='offermodel',
            name='en_procedure',
        ),
        migrations.RemoveField(
            model_name='offermodel',
            name='es_banner',
        ),
        migrations.RemoveField(
            model_name='offermodel',
            name='es_procedure',
        ),
    ]
