# Generated by Django 4.2.21 on 2025-09-15 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0002_initial'),
        ('buyers', '0001_initial'),
        ('assets_location', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorderrecipient',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='so_recipient_added_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceorderrecipient',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='so_recipients', to='buyers.offermodel'),
        ),
        migrations.AddField(
            model_name='serviceorderrecipient',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='am_pro_service_mark_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyers_offer_ampro_paid_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyers_offer_approved_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Approved By'),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyers_offer_asset', to='assets.assetmodel', verbose_name='Asset'),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='asset_in_possession_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyers_offer_asset_in_possession_by', to=settings.AUTH_USER_MODEL, verbose_name='Asset In Possession By'),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='asset_sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyers_offer_asset_sent_by', to=settings.AUTH_USER_MODEL, verbose_name='Asset Sent By'),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='buyer_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyers_offer_country', to='assets_location.assetcountrymodel', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyers_offer_user', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='payment_order_created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyers_offer_payment_order_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Payment Order Created By'),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='payment_order_sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyers_offer_payment_order_sent_by', to=settings.AUTH_USER_MODEL, verbose_name='Payment Order Sent By'),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='profitability_created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyers_offer_profitability_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Profitability Created By'),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='profitability_paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyers_offer_profitability_paid_by', to=settings.AUTH_USER_MODEL, verbose_name='Profitability Paid By'),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='propensiones_mark_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyers_offer_prop_paid_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='recovery_repatriation_foundation_mark_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyers_offer_rrf_paid_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyers_offer_reviewed_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By'),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='service_order_created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyers_offer_service_order_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Service Order Created By'),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='service_order_sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyers_offer_service_order_sent_by', to=settings.AUTH_USER_MODEL, verbose_name='Service Order Sent By'),
        ),
        migrations.AddConstraint(
            model_name='serviceorderrecipient',
            constraint=models.CheckConstraint(check=models.Q(('user__isnull', True), ('user_type__isnull', True), _negated=True), name='so_recipient_user_or_type'),
        ),
        migrations.AddConstraint(
            model_name='serviceorderrecipient',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('offer', 'user'), name='uniq_so_recipient_user'),
        ),
        migrations.AddConstraint(
            model_name='serviceorderrecipient',
            constraint=models.UniqueConstraint(condition=models.Q(('user_type__isnull', False)), fields=('offer', 'user_type'), name='uniq_so_recipient_type'),
        ),
        migrations.AddConstraint(
            model_name='offermodel',
            constraint=models.CheckConstraint(check=models.Q(('is_approved', False), ('reviewed', True), _connector='OR'), name='approved_requires_reviewed'),
        ),
        migrations.AddConstraint(
            model_name='offermodel',
            constraint=models.CheckConstraint(check=models.Q(('service_order_created_at__isnull', True), ('is_approved', True), _connector='OR'), name='so_created_requires_approved'),
        ),
        migrations.AddConstraint(
            model_name='offermodel',
            constraint=models.CheckConstraint(check=models.Q(('service_order_sent_at__isnull', True), ('service_order_created_at__isnull', False), _connector='OR'), name='so_sent_requires_so_created'),
        ),
        migrations.AddConstraint(
            model_name='offermodel',
            constraint=models.CheckConstraint(check=models.Q(('payment_order_created_at__isnull', True), ('service_order_sent_at__isnull', False), _connector='OR'), name='pay_created_requires_so_sent'),
        ),
        migrations.AddConstraint(
            model_name='offermodel',
            constraint=models.CheckConstraint(check=models.Q(('payment_order_sent_at__isnull', True), ('payment_order_created_at__isnull', False), _connector='OR'), name='pay_sent_requires_pay_created'),
        ),
        migrations.AddConstraint(
            model_name='offermodel',
            constraint=models.CheckConstraint(check=models.Q(('asset_in_possession_at__isnull', True), ('payment_order_sent_at__isnull', False), _connector='OR'), name='possession_requires_pay_sent'),
        ),
        migrations.AddConstraint(
            model_name='offermodel',
            constraint=models.CheckConstraint(check=models.Q(('asset_sent_at__isnull', True), ('asset_in_possession_at__isnull', False), _connector='OR'), name='asset_sent_requires_possession'),
        ),
        migrations.AddConstraint(
            model_name='offermodel',
            constraint=models.CheckConstraint(check=models.Q(('profitability_created_at__isnull', True), ('asset_sent_at__isnull', False), _connector='OR'), name='profit_created_requires_asset_sent'),
        ),
        migrations.AddConstraint(
            model_name='offermodel',
            constraint=models.CheckConstraint(check=models.Q(('profitability_paid_at__isnull', True), ('profitability_created_at__isnull', False), _connector='OR'), name='profit_paid_requires_profit_created'),
        ),
        migrations.AddConstraint(
            model_name='offermodel',
            constraint=models.CheckConstraint(check=models.Q(('profitability_paid_at__isnull', True), models.Q(('recovery_repatriation_foundation_paid', True), ('am_pro_service_paid', True), ('propensiones_paid', True)), _connector='OR'), name='profit_paid_requires_3_subpaids'),
        ),
    ]
