# Generated by Django 4.2.21 on 2025-09-11 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buyers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offermodel',
            name='service_order_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Service Order Created At'),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='service_order_created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyers_offer_service_order_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Service Order Created By'),
        ),
    ]
