# Generated by Django 4.2.21 on 2025-08-30 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0002_remove_offermodel_en_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offermodel',
            name='reviewed',
            field=models.BooleanField(default=False, verbose_name='Reviewed'),
        ),
    ]
