# Generated by Django 4.2.21 on 2025-09-15 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offermodel',
            name='offer_amount',
        ),
    ]
