# Generated by Django 4.2.21 on 2025-09-17 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offermodel',
            options={'ordering': ['default_order', '-created'], 'permissions': [('can_approve_offer', 'Can approve purchase orders'), ('can_review_offer', 'Can review purchase orders'), ('can_send_service_order', 'Can send service orders'), ('can_create_payment_order', 'Can create payment orders'), ('can_send_payment_order', 'Can send payment orders'), ('can_set_asset_possession', 'Can set asset in possession'), ('can_send_asset', 'Can send asset'), ('can_set_profitability', 'Can set profitability'), ('can_pay_profitability', 'Can pay profitability'), ('can_see_profitability_page', 'Can see profitability page'), ('can_see_wizard_page', 'Can see the offer workflow wizard page')], 'verbose_name': 'Purchase order', 'verbose_name_plural': 'Purchase orders'},
        ),
    ]
