# Generated by Django 4.2.21 on 2025-09-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0002_offermodel_service_order_created_at_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='offermodel',
            constraint=models.CheckConstraint(check=models.Q(('is_approved', False), ('reviewed', True), _connector='OR'), name='approved_requires_reviewed'),
        ),
        migrations.AddConstraint(
            model_name='offermodel',
            constraint=models.CheckConstraint(check=models.Q(('service_order_created_at__isnull', True), ('is_approved', True), _connector='OR'), name='so_created_requires_approved'),
        ),
        migrations.AddConstraint(
            model_name='offermodel',
            constraint=models.CheckConstraint(check=models.Q(('service_order_sent_at__isnull', True), ('service_order_created_at__isnull', False), _connector='OR'), name='so_sent_requires_so_created'),
        ),
        migrations.AddConstraint(
            model_name='offermodel',
            constraint=models.CheckConstraint(check=models.Q(('payment_order_created_at__isnull', True), ('service_order_sent_at__isnull', False), _connector='OR'), name='pay_created_requires_so_sent'),
        ),
        migrations.AddConstraint(
            model_name='offermodel',
            constraint=models.CheckConstraint(check=models.Q(('payment_order_sent_at__isnull', True), ('payment_order_created_at__isnull', False), _connector='OR'), name='pay_sent_requires_pay_created'),
        ),
        migrations.AddConstraint(
            model_name='offermodel',
            constraint=models.CheckConstraint(check=models.Q(('asset_in_possession_at__isnull', True), ('payment_order_sent_at__isnull', False), _connector='OR'), name='possession_requires_pay_sent'),
        ),
        migrations.AddConstraint(
            model_name='offermodel',
            constraint=models.CheckConstraint(check=models.Q(('asset_sent_at__isnull', True), ('asset_in_possession_at__isnull', False), _connector='OR'), name='asset_sent_requires_possession'),
        ),
        migrations.AddConstraint(
            model_name='offermodel',
            constraint=models.CheckConstraint(check=models.Q(('profitability_created_at__isnull', True), ('asset_sent_at__isnull', False), _connector='OR'), name='profit_created_requires_asset_sent'),
        ),
        migrations.AddConstraint(
            model_name='offermodel',
            constraint=models.CheckConstraint(check=models.Q(('profitability_paid_at__isnull', True), ('profitability_created_at__isnull', False), _connector='OR'), name='profit_paid_requires_profit_created'),
        ),
    ]
