# Generated by Django 4.2.21 on 2025-09-12 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buyers', '0003_alter_offermodel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrderRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('user_type', models.CharField(blank=True, choices=[('B', 'Buyer'), ('H', 'Holder'), ('R', 'Representative'), ('I', 'Intermediary')], max_length=2, null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='so_recipient_added_by', to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='so_recipients', to='buyers.offermodel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Order Recipient',
                'verbose_name_plural': 'Service Order Recipients',
                'db_table': 'apps_buyers_service_order_recipient',
                'ordering': ['default_order', '-created'],
            },
        ),
        migrations.AddConstraint(
            model_name='serviceorderrecipient',
            constraint=models.CheckConstraint(check=models.Q(('user__isnull', True), ('user_type__isnull', True), _negated=True), name='so_recipient_user_or_type'),
        ),
    ]
