# Generated by Django 4.2.21 on 2025-09-11 18:43

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0003_offermodel_approved_requires_reviewed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offermodel',
            name='offer_amount',
            field=encrypted_model_fields.fields.EncryptedPositiveIntegerField(verbose_name='Total value of the offer ($ USD)'),
        ),
    ]
