# Generated by Django 4.2.21 on 2025-08-30 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0003_offermodel_reviewed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offermodel',
            options={'ordering': ['default_order', '-created'], 'permissions': [('can_approve_offer', 'Can approve purchase orders')], 'verbose_name': '1. Purchase order', 'verbose_name_plural': '1. Purchase orders'},
        ),
        migrations.AlterField(
            model_name='offermodel',
            name='offer_amount',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=20, verbose_name='Total value of the offer ($ USD)'),
        ),
        migrations.AlterField(
            model_name='offermodel',
            name='offer_type',
            field=models.CharField(choices=[('O', 'Official purchase of the United States')], default='O', max_length=255, verbose_name='Purchase order Type'),
        ),
        migrations.AlterField(
            model_name='offermodel',
            name='quantity_type',
            field=models.CharField(choices=[('U', 'Units'), ('B', 'Boxes')], default='B', max_length=255, verbose_name='quantity type'),
        ),
    ]
