# Generated by Django 4.2.21 on 2025-09-01 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buyers', '0004_alter_offermodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offermodel',
            options={'ordering': ['default_order', '-created'], 'permissions': [('can_approve_offer', 'Can approve purchase orders'), ('can_review_offer', 'Can review purchase orders')], 'verbose_name': '1. Purchase order', 'verbose_name_plural': '1. Purchase orders'},
        ),
        migrations.AddField(
            model_name='offermodel',
            name='approved_by_timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approved By Timestamp'),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='display',
            field=models.BooleanField(default=True, verbose_name='Display'),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyers_offer_reviewed_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By'),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='reviewed_by_timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reviewed By Timestamp'),
        ),
        migrations.AlterField(
            model_name='offermodel',
            name='offer_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Total value of the offer ($ USD)'),
        ),
    ]
