# Generated by Django 4.2.21 on 2025-09-12 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0004_serviceorderrecipient_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='serviceorderrecipient',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('offer', 'user'), name='uniq_so_recipient_user'),
        ),
        migrations.AddConstraint(
            model_name='serviceorderrecipient',
            constraint=models.UniqueConstraint(condition=models.Q(('user_type__isnull', False)), fields=('offer', 'user_type'), name='uniq_so_recipient_type'),
        ),
    ]
