# Generated by Django 4.2.21 on 2025-10-09 18:25

import apps.project.specific.assets_management.buyers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0004_alter_offermodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='offermodel',
            name='offer_img',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.project.specific.assets_management.buyers.models.OfferModel.offer_image_upload_path, verbose_name='img'),
        ),
    ]
