# Generated by Django 4.2.21 on 2025-09-13 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buyers', '0005_serviceorderrecipient_uniq_so_recipient_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offermodel',
            name='am_pro_service_mark_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='am_pro_service_mark_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyers_offer_ampro_paid_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='am_pro_service_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='propensiones_mark_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='propensiones_mark_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyers_offer_prop_paid_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='propensiones_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='recovery_repatriation_foundation_mark_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='recovery_repatriation_foundation_mark_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyers_offer_rrf_paid_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='recovery_repatriation_foundation_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='offermodel',
            constraint=models.CheckConstraint(check=models.Q(('profitability_paid_at__isnull', True), models.Q(('recovery_repatriation_foundation_paid', True), ('am_pro_service_paid', True), ('propensiones_paid', True)), _connector='OR'), name='profit_paid_requires_3_subpaids'),
        ),
    ]
