# Generated by Django 4.2.21 on 2025-09-08 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buyers', '0005_alter_offermodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offermodel',
            options={'ordering': ['default_order', '-created'], 'permissions': [('can_approve_offer', 'Can approve purchase orders'), ('can_review_offer', 'Can review purchase orders'), ('can_send_service_order', 'Can send service orders'), ('can_create_payment_order', 'Can create payment orders'), ('can_send_payment_order', 'Can send payment orders'), ('can_set_asset_possession', 'Can set asset in possession'), ('can_send_asset', 'Can send asset'), ('can_set_profitability', 'Can set profitability'), ('can_pay_profitability', 'Can pay profitability')], 'verbose_name': '1. Purchase order', 'verbose_name_plural': '1. Purchase orders'},
        ),
        migrations.AddField(
            model_name='offermodel',
            name='asset_in_possession_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Asset In Possession At'),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='asset_in_possession_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyers_offer_asset_in_possession_by', to=settings.AUTH_USER_MODEL, verbose_name='Asset In Possession By'),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='asset_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Asset Sent At'),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='asset_sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyers_offer_asset_sent_by', to=settings.AUTH_USER_MODEL, verbose_name='Asset Sent By'),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='payment_order_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Payment Order Created At'),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='payment_order_created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyers_offer_payment_order_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Payment Order Created By'),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='payment_order_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Payment Order Sent At'),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='payment_order_sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyers_offer_payment_order_sent_by', to=settings.AUTH_USER_MODEL, verbose_name='Payment Order Sent By'),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='profitability_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Profitability Created At'),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='profitability_created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyers_offer_profitability_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Profitability Created By'),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='profitability_paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Profitability Paid At'),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='profitability_paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyers_offer_profitability_paid_by', to=settings.AUTH_USER_MODEL, verbose_name='Profitability Paid By'),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='service_order_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Service Order Sent At'),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='service_order_sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyers_offer_service_order_sent_by', to=settings.AUTH_USER_MODEL, verbose_name='Service Order Sent By'),
        ),
    ]
