# Generated by Django 4.2.21 on 2025-11-08 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0005_offermodel_offer_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offermodel',
            options={
                'ordering': ['default_order', '-created'],
                'permissions': [
                    ('can_approve_offer', 'Can approve purchase orders'),
                    ('can_review_offer', 'Can review purchase orders'),
                    ('can_send_service_order', 'Can send service orders'),
                    ('can_create_payment_order', 'Can create payment orders'),
                    ('can_send_payment_order', 'Can send payment orders'),
                    ('can_set_asset_possession', 'Can set asset in possession'),
                    ('can_send_asset', 'Can send asset'),
                    ('can_set_profitability', 'Can set profitability'),
                    ('can_pay_profitability', 'Can pay profitability'),
                    ('can_approve_pay_profitability', 'Can approve pay profitability'),
                    ('can_see_profitability_page', 'Can see profitability page'),
                    ('can_see_wizard_page', 'Can see the offer workflow wizard page'),
                    ('recovery_repatriation_foundation_paid', 'Mark Recovery Repatriation Foundation as paid'),
                    ('recovery_repatriation_foundation_mark_by', 'Set user who marked Recovery Repatriation Foundation as paid'),
                    ('recovery_repatriation_foundation_mark_at', 'Set timestamp when Recovery Repatriation Foundation was marked as paid'),
                    ('am_pro_service_paid', 'Mark AM PRO service as paid'),
                    ('am_pro_service_mark_by', 'Set user who marked AM PRO as paid'),
                    ('am_pro_service_mark_at', 'Set timestamp when AM PRO was marked as paid'),
                    ('propensiones_paid', 'Mark Propensiones as paid'),
                    ('propensiones_mark_by', 'Set user who marked Propensiones as paid'),
                    ('propensiones_mark_at', 'Set timestamp when Propensiones was marked as paid')
                ],
                'verbose_name': 'Purchase order', 'verbose_name_plural': 'Purchase orders'
            },
        ),
    ]
