# Generated by Django 4.2.21 on 2025-12-03 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buyers', '0006_alter_offermodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offermodel',
            options={'ordering': ['default_order', '-created'], 'permissions': [('can_approve_offer', 'Can approve purchase orders'), ('can_review_offer', 'Can review purchase orders'), ('can_send_service_order', 'Can send service orders'), ('can_create_payment_order', 'Can create payment orders'), ('can_send_payment_order', 'Can send payment orders'), ('can_set_asset_possession', 'Can set asset in possession'), ('can_send_asset', 'Can send asset'), ('can_set_profitability', 'Can set profitability'), ('can_pay_profitability', 'Can pay profitability'), ('can_approve_pay_profitability', 'Can approve pay profitability'), ('can_see_profitability_page', 'Can see profitability page'), ('can_see_wizard_page', 'Can see the offer workflow wizard page'), ('recovery_repatriation_foundation_paid', 'Mark Recovery Repatriation Foundation as paid'), ('recovery_repatriation_foundation_mark_by', 'Set user who marked Recovery Repatriation Foundation as paid'), ('recovery_repatriation_foundation_mark_at', 'Set timestamp when Recovery Repatriation Foundation was marked as paid'), ('pay_master_service_paid', 'Mark PAY MASTER service as paid'), ('pay_master_service_mark_by', 'Set user who marked PAY MASTER as paid'), ('pay_master_service_mark_at', 'Set timestamp when PAY MASTER was marked as paid'), ('propensiones_paid', 'Mark Propensiones as paid'), ('propensiones_mark_by', 'Set user who marked Propensiones as paid'), ('propensiones_mark_at', 'Set timestamp when Propensiones was marked as paid')], 'verbose_name': 'Purchase order', 'verbose_name_plural': 'Purchase orders'},
        ),
        migrations.RemoveConstraint(
            model_name='offermodel',
            name='profit_paid_requires_3_subpaids',
        ),
        migrations.RenameField(
            model_name='offermodel',
            old_name='am_pro_service_mark_at',
            new_name='pay_master_service_mark_at',
        ),
        migrations.RenameField(
            model_name='offermodel',
            old_name='am_pro_service_paid',
            new_name='pay_master_service_paid',
        ),
        migrations.RemoveField(
            model_name='offermodel',
            name='am_pro_service_mark_by',
        ),
        migrations.AddField(
            model_name='offermodel',
            name='pay_master_service_mark_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyers_offer_paymaster_paid_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='offermodel',
            constraint=models.CheckConstraint(check=models.Q(('profitability_paid_at__isnull', True), models.Q(('recovery_repatriation_foundation_paid', True), ('pay_master_service_paid', True), ('propensiones_paid', True)), _connector='OR'), name='profit_paid_requires_3_subpaids'),
        ),
    ]
