# Generated by Django 4.2.27 on 2026-09-01 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buyers", "0007_alter_offermodel_options_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="serviceorderrecipient",
            name="uniq_so_recipient_user",
        ),
        migrations.RemoveConstraint(
            model_name="serviceorderrecipient",
            name="uniq_so_recipient_type",
        ),
        migrations.AddConstraint(
            model_name="serviceorderrecipient",
            constraint=models.UniqueConstraint(
                fields=("offer", "user"), name="uniq_so_recipient_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="serviceorderrecipient",
            constraint=models.UniqueConstraint(
                fields=("offer", "user_type"), name="uniq_so_recipient_type"
            ),
        ),
    ]
