# Generated by Django 4.2.7 on 2025-01-01 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_verified_holder',
            field=models.BooleanField(default=False, verbose_name='Verified Holder'),
        ),
    ]
