# Generated by Django 4.2.21 on 2025-09-19 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usermodel_is_referred_usermodel_referred'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'permissions': [('can_view_buyer', 'Can view Buyer dashboard'), ('can_view_holder', 'Can view Client Area dashboard'), ('can_view_all_users', 'Can view all users'), ('can_view_buyers', 'Can view only buyers users'), ('can_view_holders', 'Can view only holders users'), ('can_change_password', 'Can change user password'), ('can_change_all_passwords', 'Can change all users passwords'), ('can_change_users_personal_info', 'Can change users personal information'), ('can_change_users_contact_info', 'Can change users contact information'), ('can_change_users_referred', 'Can change users referred by field'), ('can_verify_holders', 'Can verify holders'), ('can_deactivate_users', 'Can deactivate users')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
