# Generated by Django 4.2.27 on 2026-01-09 04:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_usermodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpersonalinformationmodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
