# Generated by Django 5.2.17 on 2026-09-14 02:11

import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalDocumentModel",
            fields=[
                (
                    "language",
                    models.CharField(
                        blank=True,
                        choices=[("es", "Spanish"), ("en", "English")],
                        default="es",
                        max_length=4,
                        null=True,
                        verbose_name="language",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "default_order",
                    models.PositiveIntegerField(
                        blank=True, default=1, null=True, verbose_name="priority"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("terms", "Terms and conditions"),
                            ("data_policy", "Personal data processing policy"),
                            ("privacy", "Privacy notice"),
                            ("cookies", "Cookie policy"),
                        ],
                        db_index=True,
                        help_text="Identifies the document in its URL. Never renamed.",
                        max_length=30,
                        unique=True,
                        verbose_name="Key",
                    ),
                ),
                (
                    "es_name",
                    models.CharField(max_length=200, verbose_name="Name (Spanish)"),
                ),
                (
                    "en_name",
                    models.CharField(max_length=200, verbose_name="Name (English)"),
                ),
            ],
            options={
                "verbose_name": "Legal document",
                "verbose_name_plural": "Legal documents",
                "db_table": "apps_core_legal_document",
                "ordering": ["default_order", "key"],
            },
        ),
        migrations.CreateModel(
            name="LegalDocumentVersionModel",
            fields=[
                (
                    "language",
                    models.CharField(
                        blank=True,
                        choices=[("es", "Spanish"), ("en", "English")],
                        default="es",
                        max_length=4,
                        null=True,
                        verbose_name="language",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "default_order",
                    models.PositiveIntegerField(
                        blank=True, default=1, null=True, verbose_name="priority"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="For example 1.0.0. Unique within the document.",
                        max_length=30,
                        verbose_name="Version",
                    ),
                ),
                (
                    "es_body",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True,
                        default="",
                        help_text="The wording that governs: these documents are Colombian.",
                        verbose_name="Text (Spanish)",
                    ),
                ),
                (
                    "en_body",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True,
                        default="",
                        help_text="Courtesy translation. Where they differ, Spanish rules.",
                        verbose_name="Text (English)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("APPROVED", "Approved"),
                            ("RETIRED", "Retired"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "effective_from",
                    models.DateField(
                        blank=True,
                        help_text="Set when it is approved. Article 18 of the policy requires publishing it.",
                        null=True,
                        verbose_name="In force since",
                    ),
                ),
                (
                    "change_note_es",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Goes into the notice sent to every user. Say what changed, not that something changed.",
                        verbose_name="What changed (Spanish)",
                    ),
                ),
                (
                    "change_note_en",
                    models.TextField(
                        blank=True, default="", verbose_name="What changed (English)"
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        editable=False,
                        help_text="Computed on approval, over the exact text of both languages. It is what an acceptance points to.",
                        max_length=64,
                        verbose_name="Content hash (SHA-256)",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Approved at",
                    ),
                ),
                (
                    "notify_users",
                    models.BooleanField(
                        default=True,
                        help_text="Turn it off only for a correction that changes no obligation — a typo, a broken link.",
                        verbose_name="Notify every user",
                    ),
                ),
                (
                    "notified_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Users notified at",
                    ),
                ),
                (
                    "notified_count",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="People notified"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_legal_versions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved by",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="core.legaldocumentmodel",
                        verbose_name="Document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Legal document version",
                "verbose_name_plural": "Legal document versions",
                "db_table": "apps_core_legal_document_version",
                "ordering": ["-effective_from", "-created"],
            },
        ),
        migrations.CreateModel(
            name="LegalAcceptanceModel",
            fields=[
                (
                    "language",
                    models.CharField(
                        blank=True,
                        choices=[("es", "Spanish"), ("en", "English")],
                        default="es",
                        max_length=4,
                        null=True,
                        verbose_name="language",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "default_order",
                    models.PositiveIntegerField(
                        blank=True, default=1, null=True, verbose_name="priority"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="Copied on acceptance. The proof survives even if the version row does not.",
                        max_length=64,
                        verbose_name="Hash of what was accepted",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("REGISTRATION", "On registration"),
                            ("CONTINUED_USE", "Continued use after logging in"),
                            ("EXPLICIT", "Accepted explicitly"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="How it was given",
                    ),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Accepted at",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, editable=False, null=True, verbose_name="IP address"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        default="",
                        editable=False,
                        max_length=400,
                        verbose_name="Browser",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legal_acceptances",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Data owner",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acceptances",
                        to="core.legaldocumentversionmodel",
                        verbose_name="Accepted version",
                    ),
                ),
            ],
            options={
                "verbose_name": "Legal acceptance",
                "verbose_name_plural": "Legal acceptances",
                "db_table": "apps_core_legal_acceptance",
                "ordering": ["-accepted_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="legaldocumentversionmodel",
            constraint=models.UniqueConstraint(
                fields=("document", "version"), name="uniq_version_per_legal_document"
            ),
        ),
        migrations.AddConstraint(
            model_name="legaldocumentversionmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "APPROVED"), _negated=True),
                    models.Q(
                        ("effective_from__isnull", False),
                        models.Q(("content_hash", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="approved_legal_version_needs_date_and_hash",
            ),
        ),
        migrations.AddIndex(
            model_name="legalacceptancemodel",
            index=models.Index(
                fields=["user", "accepted_at"], name="apps_core_l_user_id_a18687_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="legalacceptancemodel",
            constraint=models.UniqueConstraint(
                fields=("user", "version"), name="uniq_acceptance_per_user_and_version"
            ),
        ),
    ]
