# Generated by Django 4.2.21 on 2025-08-29 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmodel',
            name='asset_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assets_asset_assetsnames', to='assets.assetsnamesmodel', verbose_name='asset'),
        ),
    ]
