# Generated by Django 4.2.7 on 2024-12-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetmodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='assetmodel',
            name='observations',
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='en_description',
            field=models.TextField(blank=True, null=True, verbose_name='description (EN)'),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='en_observations',
            field=models.TextField(blank=True, default='', null=True, verbose_name='observations (EN)'),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='es_description',
            field=models.TextField(blank=True, null=True, verbose_name='description (ES)'),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='es_observations',
            field=models.TextField(blank=True, default='', null=True, verbose_name='observations (ES)'),
        ),
    ]
