# Generated by Django 4.2.21 on 2025-09-02 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0002_alter_assetmodel_asset_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcategorymodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets_asset_assetcategory', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
    ]
