# Generated by Django 4.2.21 on 2025-09-12 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetcategorymodel',
            options={'ordering': ['default_order', '-created'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='assetmodel',
            options={'ordering': ['default_order', '-created'], 'verbose_name': 'Asset', 'verbose_name_plural': 'Assets'},
        ),
        migrations.AlterModelOptions(
            name='assetsnamesmodel',
            options={'ordering': ['default_order', '-created'], 'verbose_name': 'Asset Name', 'verbose_name_plural': 'Asset Names'},
        ),
    ]
