# Generated by Django 4.2.7 on 2024-12-17 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_remove_assetmodel_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetmodel',
            options={'ordering': ['default_order', '-created'], 'verbose_name': '3. Asset', 'verbose_name_plural': '3. Assets'},
        ),
        migrations.AlterModelOptions(
            name='assetsnamesmodel',
            options={'ordering': ['default_order', '-created'], 'verbose_name': '1. Asset Name', 'verbose_name_plural': '1. Asset Names'},
        ),
    ]
