# Generated by Django 4.2.21 on 2025-09-02 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_assetcategorymodel_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetcategorymodel',
            old_name='description',
            new_name='en_description',
        ),
        migrations.AddField(
            model_name='assetcategorymodel',
            name='es_description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
