# Generated by Django 4.2.7 on 2025-01-01 22:33

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_assetmodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreRegistrationAssetModel',
            fields=[
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('asset_name', models.CharField(choices=[('ZIMBAWES', 'Zimbawes'), ('EXOTICS', 'Exotics'), ('GERMAN PARCHMENTS', 'German Parchments'), ('GERMAN', 'German'), ('DRAGONS', 'Dragons'), ('MICRO INGOTS', 'Micro Ingots'), ('DINARS', 'Dinars'), ('ONE MILLION DOLLAR BILLS', 'One Million Dollar Bills'), ('AGROCHEQUES', 'Agrocheques'), ('SUPER PECHILES', 'Super Pechiles'), ('COINS', 'Coins'), ('LION HEADS', 'Lion Heads'), ('SHANGHAI BANKNOTES', 'Shanghai Banknotes'), ('BLACK DRAGONS', 'Black Dragons'), ('BLACK EAGLES', 'Black Eagles'), ('OTHERS', 'Others')], default='OTHERS', max_length=255, verbose_name='asset name')),
                ('es_description', models.TextField(blank=True, null=True, verbose_name='description (ES)')),
                ('en_description', models.TextField(blank=True, null=True, verbose_name='description (EN)')),
                ('es_observations', models.TextField(blank=True, default='', null=True, verbose_name='observations (ES)')),
                ('en_observations', models.TextField(blank=True, default='', null=True, verbose_name='observations (EN)')),
            ],
            options={
                'verbose_name': '4. Pre-Registration Asset',
                'verbose_name_plural': '4. Pre-Registration Assets',
                'db_table': 'apps_assets_preregistrationasset',
                'ordering': ['default_order', '-created'],
            },
        ),
    ]
