# Generated by Django 4.2.7 on 2025-01-02 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0004_preregistrationassetmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='preregistrationassetmodel',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preregistrationasset_preregistrationasset_user', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
    ]
