# Generated by Django 4.2.21 on 2025-09-03 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_rename_description_assetcategorymodel_en_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetcategorymodel',
            name='es_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='category (ES)'),
        ),
        migrations.AlterField(
            model_name='assetsnamesmodel',
            name='en_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='asset (en)'),
        ),
        migrations.AlterField(
            model_name='assetsnamesmodel',
            name='es_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='asset (es)'),
        ),
    ]
