# Generated by Django 4.2.7 on 2025-01-03 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_preregistrationassetmodel_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='preregistrationassetmodel',
            name='has_asset',
            field=models.BooleanField(default=False, verbose_name='Has Item'),
        ),
    ]
