# Generated by Django 4.2.27 on 2026-08-29 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandRunModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('command', models.CharField(db_index=True, max_length=100, verbose_name='Command')),
                ('arguments', models.JSONField(blank=True, default=dict, help_text='The values as they were filled in the form.', verbose_name='Arguments')),
                ('command_line', models.TextField(blank=True, default='', help_text='What was actually run, argument by argument.', verbose_name='Command line')),
                ('status', models.CharField(choices=[('SUCCESS', 'Finished'), ('FAILED', 'Failed'), ('TIMED_OUT', 'Cut off by timeout'), ('REFUSED', 'Refused')], db_index=True, max_length=20, verbose_name='Status')),
                ('exit_code', models.IntegerField(blank=True, null=True, verbose_name='Exit code')),
                ('duration_seconds', models.FloatField(default=0.0, verbose_name='Duration (s)')),
                ('output', models.TextField(blank=True, default='', verbose_name='Output')),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Client IP')),
                ('run_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ops_command_runs', to=settings.AUTH_USER_MODEL, verbose_name='Run by')),
            ],
            options={
                'verbose_name': 'Command run',
                'verbose_name_plural': 'Command runs',
                'db_table': 'apps_ops_command_run',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['command', '-created'], name='apps_ops_co_command_fddfbe_idx'), models.Index(fields=['status'], name='apps_ops_co_status_0ab5e9_idx')],
            },
        ),
    ]
