# Generated by Django 4.2.27 on 2026-01-08 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import encrypted_model_fields.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTypesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('name', models.CharField(choices=[('ASSET_AEGIS', 'Asset Certificate (AEGIS)'), ('IDONEITY', 'Idoneity'), ('EMPLOYEE_VERIFICATION_IPCON', 'Employee Verification Ipcon'), ('EMPLOYEE_VERIFICATION_PROPENSIONES', 'Employee Verification Propensiones')], max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Certificate Type',
                'verbose_name_plural': 'Certificate Types',
                'db_table': 'apps_certificates_certificate_types',
                'ordering': ['default_order', '-created'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVerificationModel',
            fields=[
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_code', models.CharField(max_length=16, unique=True, verbose_name='Public verification code')),
                ('uuid_prefix', models.CharField(editable=False, max_length=8, unique=True)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='certificates/documents/', verbose_name='Document file')),
                ('document_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('delivery_method', models.CharField(choices=[('DIGITAL', 'Digital'), ('PHYSICAL', 'Physical'), ('NONE', 'Not delivered')], default='NONE', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent at')),
                ('issued_at', models.DateField(verbose_name='Issued at')),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='Expires at')),
                ('daily_validation_enabled', models.BooleanField(default=False)),
                ('daily_validation_token', models.CharField(blank=True, max_length=64, null=True)),
                ('daily_validation_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Document Verification',
                'verbose_name_plural': 'Document Verification',
                'db_table': 'apps_certificates_document_verification',
                'ordering': ['default_order', '-created'],
                'indexes': [models.Index(fields=['public_code'], name='apps_certif_public__caa7bb_idx'), models.Index(fields=['uuid_prefix'], name='apps_certif_uuid_pr_0d5c93_idx'), models.Index(fields=['expires_at'], name='apps_certif_expires_c9b602_idx')],
            },
        ),
        migrations.CreateModel(
            name='CertificateUserModel',
            fields=[
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Names')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Last name')),
                ('document_type', models.CharField(choices=[('CC', 'Citizen ID (CC)'), ('PA', 'Passport (PA)'), ('UNIQUE_CODE', 'Unique Code')], default='CC', max_length=15, verbose_name='Document type')),
                ('document_number', encrypted_model_fields.fields.EncryptedCharField(verbose_name='Document number')),
                ('document_number_hash', models.CharField(default='', editable=False, max_length=64)),
                ('approved', models.BooleanField(default=True, verbose_name='Approved')),
                ('approval_date', models.DateField(blank=True, null=True, verbose_name='Approval date')),
                ('issued_at', models.DateField(blank=True, help_text='Legal issuance date of the certificate', null=True, verbose_name='Issued at')),
                ('expires_at', models.DateField(blank=True, db_index=True, null=True, verbose_name='Expires at')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Revoked at')),
                ('revocation_reason', models.TextField(blank=True, null=True, verbose_name='Revocation reason')),
                ('is_revoked', models.BooleanField(default=False, verbose_name='Is revoked')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates_certificate_user_approvedby', to=settings.AUTH_USER_MODEL, verbose_name='Approved by')),
                ('certificate_type', models.ForeignKey(blank=True, default='ASSET_AEGIS', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates_certificate_certificate_type', to='certificates.certificatetypesmodel', verbose_name='Certificate type')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates_certificate_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Verification',
                'verbose_name_plural': 'User Verification',
                'db_table': 'apps_certificates_user_verification',
                'ordering': ['default_order', '-created'],
                'unique_together': {('document_number', 'document_type', 'certificate_type')},
            },
        ),
    ]
