# Generated by Django 4.2.27 on 2026-01-11 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import encrypted_model_fields.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVerificationModel',
            fields=[
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_uuid', models.CharField(blank=True, max_length=36, null=True, unique=True, verbose_name='Public UUID')),
                ('uuid_prefix', models.CharField(blank=True, editable=False, max_length=8, null=True, unique=True, verbose_name='UUID Prefix')),
                ('public_code', models.CharField(blank=True, db_index=True, max_length=4, null=True, unique=True, verbose_name='Public verification code')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Names')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Last name')),
                ('document_number_cc', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, verbose_name='Document number CC')),
                ('document_number_pa', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, verbose_name='Document number PA')),
                ('passport_expiration_date', models.DateField(blank=True, null=True, verbose_name='Passport expiration date')),
                ('document_number_cc_hash', models.CharField(blank=True, editable=False, max_length=64, null=True)),
                ('document_number_pa_hash', models.CharField(blank=True, editable=False, max_length=64, null=True)),
                ('approved', models.BooleanField(default=True, verbose_name='Approved')),
                ('approval_date', models.DateField(blank=True, null=True, verbose_name='Approval date')),
                ('certificate_type', models.CharField(choices=[('IDONEITY', 'Idoneity'), ('EM_IPCON', 'Employee Badge (IPCON)'), ('EM_PROPENSIONES', 'Employee Badge (Propensiones)')], max_length=100, verbose_name='Certificate type')),
                ('issued_at', models.DateField(blank=True, help_text='Legal issuance date of the certificate', null=True, verbose_name='Issued at')),
                ('expires_at', models.DateField(blank=True, db_index=True, null=True, verbose_name='Expires at')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Revoked at')),
                ('revocation_reason', models.TextField(blank=True, null=True, verbose_name='Revocation reason')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates_certificate_user_approvedby', to=settings.AUTH_USER_MODEL, verbose_name='Approved by')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates_certificate_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Verification',
                'verbose_name_plural': 'User Verification',
                'db_table': 'apps_certificates_user_verification',
                'ordering': ['default_order', '-created'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVerificationModel',
            fields=[
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_title', models.CharField(max_length=200, verbose_name='Document title')),
                ('public_code', models.CharField(blank=True, db_index=True, max_length=4, null=True, unique=True, verbose_name='Public verification code')),
                ('uuid_prefix', models.CharField(blank=True, editable=False, max_length=8, null=True, unique=True)),
                ('certificate_type', models.CharField(choices=[('ASSET_AEGIS', 'Asset Certificate (AEGIS)'), ('GENERIC', 'Generic Document')], max_length=100, verbose_name='Certificate type')),
                ('document_file', models.FileField(blank=True, null=True, upload_to='certificates/documents/', verbose_name='Document file')),
                ('document_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('delivery_method', models.CharField(choices=[('DIGITAL', 'Digital'), ('PHYSICAL', 'Physical'), ('NONE', 'Not delivered')], default='NONE', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent at')),
                ('issued_at', models.DateField(verbose_name='Issued at')),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='Expires at')),
            ],
            options={
                'verbose_name': 'Document Verification',
                'verbose_name_plural': 'Document Verification',
                'db_table': 'apps_certificates_document_verification',
                'ordering': ['default_order', '-created'],
                'indexes': [models.Index(fields=['public_code'], name='apps_certif_public__caa7bb_idx'), models.Index(fields=['uuid_prefix'], name='apps_certif_uuid_pr_0d5c93_idx'), models.Index(fields=['expires_at'], name='apps_certif_expires_c9b602_idx')],
            },
        ),
        migrations.CreateModel(
            name='CertificateViewLogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('anonymous_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Anonymous email')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User agent')),
                ('viewed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Viewed at')),
                ('certificate_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='certificates.userverificationmodel', verbose_name='User Certificate')),
                ('document_verification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='certificates.documentverificationmodel', verbose_name='Document Verification')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_views', to=settings.AUTH_USER_MODEL, verbose_name='Authenticated user')),
            ],
            options={
                'verbose_name': 'Certificate View Log',
                'verbose_name_plural': 'Certificate View Logs',
                'db_table': 'apps_certificates_view_log',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='userverificationmodel',
            index=models.Index(fields=['expires_at'], name='apps_certif_expires_68e66f_idx'),
        ),
        migrations.AddIndex(
            model_name='userverificationmodel',
            index=models.Index(fields=['certificate_type'], name='apps_certif_certifi_1f6e6a_idx'),
        ),
        migrations.AddIndex(
            model_name='userverificationmodel',
            index=models.Index(fields=['approved'], name='apps_certif_approve_b82786_idx'),
        ),
        migrations.AddConstraint(
            model_name='userverificationmodel',
            constraint=models.UniqueConstraint(fields=('document_number_cc_hash', 'certificate_type'), name='uniq_cc_per_certificate_type'),
        ),
        migrations.AddConstraint(
            model_name='userverificationmodel',
            constraint=models.UniqueConstraint(fields=('document_number_pa_hash', 'certificate_type'), name='uniq_pa_per_certificate_type'),
        ),
        migrations.AddIndex(
            model_name='certificateviewlogmodel',
            index=models.Index(fields=['certificate_user'], name='apps_certif_certifi_72eb18_idx'),
        ),
        migrations.AddIndex(
            model_name='certificateviewlogmodel',
            index=models.Index(fields=['document_verification'], name='apps_certif_documen_b8ed3a_idx'),
        ),
        migrations.AddIndex(
            model_name='certificateviewlogmodel',
            index=models.Index(fields=['user'], name='apps_certif_user_id_25db5c_idx'),
        ),
        migrations.AddIndex(
            model_name='certificateviewlogmodel',
            index=models.Index(fields=['anonymous_email'], name='apps_certif_anonymo_80377f_idx'),
        ),
        migrations.AddIndex(
            model_name='certificateviewlogmodel',
            index=models.Index(fields=['viewed_at'], name='apps_certif_viewed__3e08e8_idx'),
        ),
    ]
