# Generated by Django 4.2.27 on 2026-01-29 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverificationmodel',
            name='employee_photo',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/employee_photos/', verbose_name='Employee photo'),
        ),
    ]
