# Generated by Django 4.2.7 on 2025-01-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatemodel',
            name='certificate_type',
            field=models.CharField(default='IDONEITY', max_length=100, verbose_name='Certificate type'),
        ),
    ]
