# Generated by Django 4.2.27 on 2026-01-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_userverificationmodel_employee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentverificationmodel',
            name='delivery_method',
            field=models.CharField(choices=[('DIGITAL', 'Digital'), ('PHYSICAL', 'Physical'), ('BOTH', 'Digital and Physical'), ('NONE', 'Not delivered')], default='NONE', max_length=10),
        ),
    ]
