# Generated by Django 4.2.7 on 2025-01-04 20:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_certificatemodel_certificate_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTypesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('name', models.CharField(choices=[('IDONEITY', 'Idoneity'), ('SOVEREIGN_PURCHASE', 'Sovereign Purchase')], max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Certificate Type',
                'verbose_name_plural': 'Certificate Types',
                'db_table': 'apps_certificates_certificate_types',
                'ordering': ['default_order', '-created'],
            },
        ),
        migrations.AlterField(
            model_name='certificatemodel',
            name='certificate_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates_certificate_certificate_type', to='certificates.certificatetypesmodel', verbose_name='Certificate type'),
        ),
    ]
