# Generated by Django 4.2.27 on 2026-08-25 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code_gen', '0002_codesequencemodel_stamplayoutmodel_and_more'),
        ('certificates', '0003_alter_documentverificationmodel_delivery_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentverificationmodel',
            name='certification_status',
            field=models.CharField(choices=[('DRAFT', 'Draft (original uploaded, not certified)'), ('CERTIFIED', 'Certified'), ('REVOKED', 'Revoked')], db_index=True, default='DRAFT', max_length=20, verbose_name='Certification status'),
        ),
        migrations.AddField(
            model_name='documentverificationmodel',
            name='certified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Certified at'),
        ),
        migrations.AddField(
            model_name='documentverificationmodel',
            name='certified_content_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Certified content hash'),
        ),
        migrations.AddField(
            model_name='documentverificationmodel',
            name='code_hash_fragment',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Hash fragment in the code'),
        ),
        migrations.AddField(
            model_name='documentverificationmodel',
            name='code_initials',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Certificate initials'),
        ),
        migrations.AddField(
            model_name='documentverificationmodel',
            name='code_payload',
            field=models.TextField(blank=True, default='', verbose_name='Code payload'),
        ),
        migrations.AddField(
            model_name='documentverificationmodel',
            name='code_sequence',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20, verbose_name='Autonomous sequence'),
        ),
        migrations.AddField(
            model_name='documentverificationmodel',
            name='public_copy_content_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Distributable copy content hash'),
        ),
        migrations.AddField(
            model_name='documentverificationmodel',
            name='public_copy_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/documents/public/', verbose_name='Distributable digital copy'),
        ),
        migrations.AddField(
            model_name='documentverificationmodel',
            name='public_copy_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Distributable copy hash'),
        ),
        migrations.AddField(
            model_name='documentverificationmodel',
            name='qr_payload',
            field=models.TextField(blank=True, default='', verbose_name='QR payload'),
        ),
        migrations.AddField(
            model_name='documentverificationmodel',
            name='source_content_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Original content hash'),
        ),
        migrations.AddField(
            model_name='documentverificationmodel',
            name='source_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/documents/source/', verbose_name='Original document (without codes)'),
        ),
        migrations.AddField(
            model_name='documentverificationmodel',
            name='source_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Original file hash'),
        ),
        migrations.AddField(
            model_name='documentverificationmodel',
            name='stamp_layout',
            field=models.ForeignKey(blank=True, help_text='Where the QR and the barcode are placed inside the PDF. Leave empty to use the default layout.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='code_gen.stamplayoutmodel', verbose_name='Stamp layout'),
        ),
        migrations.AddField(
            model_name='documentverificationmodel',
            name='watermark_token',
            field=models.CharField(blank=True, default='', editable=False, max_length=128, verbose_name='Watermark token'),
        ),
        migrations.AlterField(
            model_name='documentverificationmodel',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/documents/', verbose_name='Certified document (with codes)'),
        ),
        migrations.AlterField(
            model_name='documentverificationmodel',
            name='document_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='Certified file hash'),
        ),
        migrations.AlterField(
            model_name='documentverificationmodel',
            name='public_code',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True, verbose_name='Public verification code'),
        ),
        migrations.AddIndex(
            model_name='documentverificationmodel',
            index=models.Index(fields=['certification_status'], name='apps_certif_certifi_18c24f_idx'),
        ),
    ]
