# Generated by Django 4.2.27 on 2026-08-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_documentverificationmodel_certification_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentverificationmodel',
            name='delivery_method',
            field=models.CharField(choices=[('DIGITAL', 'Digital'), ('PHYSICAL', 'Physical'), ('BOTH', 'Digital and Physical'), ('NONE', 'Not delivered')], default='NONE', max_length=10, verbose_name='Delivery method'),
        ),
        migrations.AlterField(
            model_name='documentverificationmodel',
            name='uuid_prefix',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True, unique=True, verbose_name='UUID Prefix'),
        ),
    ]
