# Generated by Django 4.2.7 on 2025-01-08 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0005_alter_certificatemodel_certificate_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='certificatemodel',
            unique_together={('document_number', 'document_type', 'certificate_type')},
        ),
    ]
