# Generated by Django 4.2.27 on 2026-08-29 04:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
        ('certificates', '0005_alter_documentverificationmodel_delivery_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AegisSummaryDocumentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('code', models.CharField(help_text='For example AEGIS-1, AEGIS-2…', max_length=30, verbose_name='Code in the box')),
                ('document_type_label', models.CharField(blank=True, default='', help_text='As it appears in the master payload.', max_length=200, verbose_name='Document type')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='summary_memberships', to='certificates.documentverificationmodel', verbose_name='Document')),
            ],
            options={
                'verbose_name': 'Summary member',
                'verbose_name_plural': 'Summary members',
                'db_table': 'apps_certificates_aegis_summary_document',
                'ordering': ['default_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='AegisSummaryModel',
            fields=[
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Summary title')),
                ('public_code', models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True, verbose_name='Public verification code')),
                ('uuid_prefix', models.CharField(blank=True, editable=False, max_length=8, null=True, unique=True, verbose_name='UUID Prefix')),
                ('asset_label', models.CharField(blank=True, default='', help_text='Human readable name of the asset. Only a label: the binding is made through the asset UUID.', max_length=200, verbose_name='Asset label')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft (members selected, not sealed)'), ('SEALED', 'Sealed (master hash computed)'), ('CERTIFIED', 'Certified (summary document issued)')], db_index=True, default='DRAFT', max_length=20, verbose_name='Status')),
                ('canonical_payload', models.TextField(blank=True, default='', help_text='The exact bytes the master hash was computed over (JCS/RFC8785). Stored verbatim so anyone can recompute it.', verbose_name='Canonical payload')),
                ('master_hash', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Master hash')),
                ('sealed_at', models.DateTimeField(blank=True, null=True, verbose_name='Sealed at')),
                ('issued_at', models.DateField(blank=True, null=True, verbose_name='Issued at')),
                ('asset', models.ForeignKey(blank=True, help_text='The asset this box of certificates belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aegis_summaries', to='assets.assetmodel', verbose_name='Asset')),
                ('documents', models.ManyToManyField(related_name='aegis_summaries', through='certificates.AegisSummaryDocumentModel', to='certificates.documentverificationmodel', verbose_name='Documents')),
                ('summary_document', models.OneToOneField(blank=True, help_text='The certified PDF that carries the master hash and the barcodes of every member. Issued after sealing, never part of the hash.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summary_of', to='certificates.documentverificationmodel', verbose_name='Summary document')),
            ],
            options={
                'verbose_name': 'AEGIS Summary',
                'verbose_name_plural': 'AEGIS Summaries',
                'db_table': 'apps_certificates_aegis_summary',
                'ordering': ['default_order', '-created'],
            },
        ),
        migrations.AddField(
            model_name='aegissummarydocumentmodel',
            name='summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='certificates.aegissummarymodel', verbose_name='Summary'),
        ),
        migrations.AddIndex(
            model_name='aegissummarymodel',
            index=models.Index(fields=['public_code'], name='apps_certif_public__7656e2_idx'),
        ),
        migrations.AddIndex(
            model_name='aegissummarymodel',
            index=models.Index(fields=['uuid_prefix'], name='apps_certif_uuid_pr_5eb71c_idx'),
        ),
        migrations.AddIndex(
            model_name='aegissummarymodel',
            index=models.Index(fields=['master_hash'], name='apps_certif_master__d1e50c_idx'),
        ),
        migrations.AddConstraint(
            model_name='aegissummarydocumentmodel',
            constraint=models.UniqueConstraint(fields=('summary', 'document'), name='uniq_document_per_summary'),
        ),
        migrations.AddConstraint(
            model_name='aegissummarydocumentmodel',
            constraint=models.UniqueConstraint(fields=('summary', 'code'), name='uniq_code_per_summary'),
        ),
    ]
