# Generated by Django 4.2.27 on 2026-08-31 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0002_initial"),
        ("certificates", "0006_aegissummarydocumentmodel_aegissummarymodel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aegissummarydocumentmodel",
            name="code",
            field=models.CharField(
                help_text="For example AEGIS-1, AEGIS-2…",
                max_length=30,
                verbose_name="Code in the summary",
            ),
        ),
        migrations.AlterField(
            model_name="aegissummarymodel",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                help_text="The asset this summary of certificates belongs to.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="aegis_summaries",
                to="assets.assetmodel",
                verbose_name="Asset",
            ),
        ),
    ]
