# Generated by Django 5.2.17 on 2026-09-15 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0007_alter_aegissummarydocumentmodel_code_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="documentverificationmodel",
            name="holder",
            field=models.ForeignKey(
                blank=True,
                help_text="The user this certificate was issued for. They can see it in the code history, read-only: never the original file, the symbols or where they were stamped.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="held_certificates",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Holder",
            ),
        ),
    ]
