# Generated by Django 5.2.17 on 2026-09-15 19:42, hand-edited.
#
# Un certificado puede ser de varias personas a la vez -- los integrantes de
# una organizacion, no solo quien lo tramito -- y el FK `holder` solo dejaba
# elegir una. Se pasa a `holders` (M2M), llevando primero lo que ya hubiera en
# `holder` a la tabla nueva y solo despues quitando el campo viejo: al reves,
# el dato se perderia antes de copiarlo a ningun sitio.

from django.conf import settings
from django.db import migrations, models


def copy_holder_into_holders(apps, schema_editor):
    DocumentVerificationModel = apps.get_model(
        'certificates', 'DocumentVerificationModel')

    documents = (
        DocumentVerificationModel.objects
        .filter(holder__isnull=False)
        .only('pk', 'holder_id')
    )

    for document in documents:
        document.holders.add(document.holder_id)


def copy_first_holder_back_into_holder(apps, schema_editor):
    """
    Vuelta atras, a sabiendas de que es incompleta.

    Un FK solo puede llevar a una persona: si el certificado tiene varias, se
    queda con la primera (por id, para que sea reproducible) y las demas se
    pierden. Es lo unico que se puede hacer al deshacer un M2M sobre un campo
    que nunca tuvo sitio para mas de uno.
    """
    DocumentVerificationModel = apps.get_model(
        'certificates', 'DocumentVerificationModel')

    for document in DocumentVerificationModel.objects.all():
        first_holder = document.holders.order_by('pk').first()
        if first_holder is not None:
            document.holder_id = first_holder.pk
            document.save(update_fields=['holder'])


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0008_documentverificationmodel_holder"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="documentverificationmodel",
            name="holders",
            field=models.ManyToManyField(
                blank=True,
                help_text="The users this certificate was issued for. They can see it in the code history, read-only: never the original file, the symbols or where they were stamped.",
                related_name="held_certificates",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Holders",
            ),
        ),
        migrations.RunPython(
            copy_holder_into_holders,
            copy_first_holder_back_into_holder,
        ),
        migrations.RemoveField(
            model_name="documentverificationmodel",
            name="holder",
        ),
    ]
