# Generated by Django 5.2.17 on 2026-09-30 05:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0009_documentverificationmodel_holder_to_holders'),
        ('code_gen', '0008_coderegistrationmodel_qr_logo_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentverificationmodel',
            name='external_idempotency_key',
            field=models.CharField(blank=True, editable=False, max_length=128, null=True, verbose_name='External idempotency key'),
        ),
        migrations.AddField(
            model_name='documentverificationmodel',
            name='external_issuer',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Slug of the external platform that sent this document to be certified. Empty for documents issued by GEA itself.', max_length=40, null=True, verbose_name='External issuer'),
        ),
        migrations.AddField(
            model_name='documentverificationmodel',
            name='external_reference',
            field=models.CharField(blank=True, default='', editable=False, help_text='Identifier of the case or record in the external platform.', max_length=200, verbose_name='External reference'),
        ),
        migrations.AddField(
            model_name='documentverificationmodel',
            name='revocation_reason',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='Revocation reason'),
        ),
        migrations.AddField(
            model_name='documentverificationmodel',
            name='revoked_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Revoked at'),
        ),
        migrations.AddConstraint(
            model_name='documentverificationmodel',
            constraint=models.UniqueConstraint(fields=('external_issuer', 'external_idempotency_key'), name='uniq_document_external_idempotency'),
        ),
    ]
