# Generated by Django 4.2.27 on 2026-09-01 02:33

import apps.project.common.pqrs.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import encrypted_model_fields.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PQRSRequest",
            fields=[
                (
                    "language",
                    models.CharField(
                        blank=True,
                        choices=[("es", "Spanish"), ("en", "English")],
                        default="es",
                        max_length=4,
                        null=True,
                        verbose_name="language",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "default_order",
                    models.PositiveIntegerField(
                        blank=True, default=1, null=True, verbose_name="priority"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "radicado",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="What the person quotes when asking about their request.",
                        max_length=20,
                        unique=True,
                        verbose_name="Reference number",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("ACCESS", "Access"),
                            ("UPDATE", "Update"),
                            ("RECTIFICATION", "Rectification"),
                            ("DELETION", "Deletion"),
                            ("PETITION", "Petition"),
                            ("COMPLAINT", "Complaint"),
                            ("QUERY", "Query"),
                        ],
                        max_length=20,
                        verbose_name="Request type",
                    ),
                ),
                (
                    "person_type",
                    models.CharField(
                        choices=[
                            ("NATURAL", "Natural person"),
                            ("LEGAL", "Legal entity"),
                        ],
                        default="NATURAL",
                        max_length=10,
                        verbose_name="Person type",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=150, verbose_name="Names"),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Surnames"
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Company name"
                    ),
                ),
                (
                    "legal_representative",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Legal representative"
                    ),
                ),
                (
                    "identification_type",
                    models.CharField(
                        choices=[
                            ("CC", "Citizen ID"),
                            ("CE", "Foreign ID"),
                            ("PA", "Passport"),
                            ("NIT", "NIT"),
                        ],
                        max_length=5,
                        verbose_name="Identification type",
                    ),
                ),
                (
                    "identification_number",
                    encrypted_model_fields.fields.EncryptedCharField(
                        verbose_name="Identification number"
                    ),
                ),
                ("country", models.CharField(max_length=100, verbose_name="Country")),
                ("city", models.CharField(max_length=100, verbose_name="City")),
                (
                    "address",
                    encrypted_model_fields.fields.EncryptedCharField(
                        verbose_name="Address"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email address"),
                ),
                (
                    "phone_code",
                    models.CharField(
                        default="+57", max_length=7, verbose_name="Phone code"
                    ),
                ),
                (
                    "phone_number",
                    encrypted_model_fields.fields.EncryptedCharField(
                        verbose_name="Mobile"
                    ),
                ),
                (
                    "identity_document",
                    models.FileField(
                        blank=True,
                        help_text="To prove who is making the request.",
                        null=True,
                        upload_to=apps.project.common.pqrs.models.identity_document_path,
                        verbose_name="Identity document",
                    ),
                ),
                (
                    "legal_existence_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.project.common.pqrs.models.legal_existence_path,
                        verbose_name="Certificate of existence and legal representation",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "use_titular_contact",
                    models.BooleanField(
                        default=True, verbose_name="Use the contact details above"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Contact email"
                    ),
                ),
                (
                    "contact_phone",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, verbose_name="Contact mobile"
                    ),
                ),
                (
                    "contact_landline",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, verbose_name="Landline"
                    ),
                ),
                (
                    "accepted_terms",
                    models.BooleanField(default=False, verbose_name="Terms accepted"),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Terms accepted at",
                    ),
                ),
                (
                    "submitted_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Submitted from",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Received"),
                            ("IN_PROGRESS", "In progress"),
                            ("AWAITING_AMENDMENT", "Awaiting amendment"),
                            ("EXTENDED", "Extended"),
                            ("ANSWERED", "Answered"),
                            ("TRANSFERRED", "Transferred to another authority"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        db_index=True,
                        default="RECEIVED",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "received_on",
                    models.DateField(
                        db_index=True, editable=False, verbose_name="Received on"
                    ),
                ),
                (
                    "due_on",
                    models.DateField(
                        db_index=True,
                        editable=False,
                        help_text="Calculated in business days when it comes in.",
                        verbose_name="Due on",
                    ),
                ),
                (
                    "extended",
                    models.BooleanField(default=False, verbose_name="Extended"),
                ),
                (
                    "answered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Answered at"
                    ),
                ),
                ("answer", models.TextField(blank=True, verbose_name="Answer")),
                (
                    "internal_notes",
                    models.TextField(
                        blank=True,
                        help_text="Not shown to the person who filed the request.",
                        verbose_name="Internal notes",
                    ),
                ),
                (
                    "answered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pqrs_answered",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Answered by",
                    ),
                ),
            ],
            options={
                "verbose_name": "PQRS request",
                "verbose_name_plural": "PQRS requests",
                "db_table": "apps_pqrs_request",
                "ordering": ["default_order", "-created"],
                "indexes": [
                    models.Index(
                        fields=["status", "due_on"],
                        name="apps_pqrs_r_status_abcd7a_idx",
                    ),
                    models.Index(
                        fields=["request_type"], name="apps_pqrs_r_request_fce25e_idx"
                    ),
                ],
            },
        ),
    ]
