from django.urls import path

from apps.project.specific.assets_management.buyers.views import (
    OfferDetailView,
    OfferSoftDeleteView,
    OfferUpdateView,
    PurchaseOrderCreateView,
    PurchaseOrdersView,
    OfferApprovalWizardPageView,
    OfferApprovalWizardPartialView,
    OfferApprovalWizardActionView,
    ProfitabilityTemplateView,
    InventoryTemplateView,
    AssetCreditFormTemplateView,
    AssetCreditFormSuccessTemplateView,
    OrionSchedulerView,
)

app_name = "buyers"

urlpatterns = [
    path(
        'buyer/asset/purchase-order/<uuid:id>/detail/',
        OfferDetailView.as_view(),
        name='offer_details'
    ),
    path(
        'buyer/asset/purchase-order/<uuid:pk>/update/',
        OfferUpdateView.as_view(),
        name='offer_update'
    ),
    path(
        'buyer/asset/purchase-order/<uuid:id>/delete/',
        OfferSoftDeleteView.as_view(),
        name='offer_delete'
    ),
    path(
        'buyer/asset/purchase-orders/',
        PurchaseOrdersView.as_view(),
        name='buyer_index'
    ),
    path(
        'buyer/asset/purchase-order/add/',
        PurchaseOrderCreateView.as_view(),
        name='buyer_create'
    ),
    path(
        "po/<uuid:id>/wizard/",
        OfferApprovalWizardPageView.as_view(),
        name="offer_wizard_page"
    ),
    path(
        "po/<uuid:id>/wizard/partial/",
        OfferApprovalWizardPartialView.as_view(),
        name="offer_wizard_partial"
    ),
    path(
        "po/<uuid:id>/wizard/action/",
        OfferApprovalWizardActionView.as_view(),
        name="offer_wizard_action"
    ),
    path(
        "profitability/",
        ProfitabilityTemplateView.as_view(),
        name="profitability_view"
    ),
    path(
        "buyer/inventory/",
        InventoryTemplateView.as_view(),
        name="inventory_view"
    ),
    path(
        "buyer/hermes/form/",
        AssetCreditFormTemplateView.as_view(),
        name="hermes_form"
    ),
    path(
        "buyer/hermes/form/success/",
        AssetCreditFormSuccessTemplateView.as_view(),
        name="hermes_form_success"
    ),
    path(
        "buyer/orion/scheduler/",
        OrionSchedulerView.as_view(),
        name="orion_scheduler"
    ),
]
