# Generated by Django 4.2.27 on 2026-01-27 04:57

import apps.project.specific.documents.video_masonry.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('file', models.FileField(upload_to=apps.project.specific.documents.video_masonry.models.upload_to)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], editable=False, max_length=10)),
                ('caption', models.TextField(blank=True, null=True)),
                ('categories', models.CharField(blank=True, help_text='Categories separated by commas. E.g: historical, exotic, scrolls', max_length=500, null=True)),
                ('remove_audio', models.BooleanField(default=True)),
                ('size_bytes', models.BigIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['media_type', 'created_at'], name='video_mason_media_t_440bf0_idx')],
            },
        ),
    ]
