# Generated by Django 4.2.27 on 2026-01-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_masonry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='categories_key',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Derived field for filtering. Do not edit.', max_length=650, null=True),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['categories_key'], name='video_mason_categor_8be791_idx'),
        ),
    ]
