# Generated by Django 4.2.27 on 2026-01-27 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video_masonry', '0002_mediaasset_categories_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAssetInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('action', models.CharField(choices=[('view', 'View'), ('download', 'Download')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MediaAssetUserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('downloads_count', models.PositiveIntegerField(default=0)),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='mediaasset',
            options={'ordering': ['-created', '-id']},
        ),
        migrations.RemoveIndex(
            model_name='mediaasset',
            name='video_mason_media_t_440bf0_idx',
        ),
        migrations.RemoveIndex(
            model_name='mediaasset',
            name='video_mason_categor_8be791_idx',
        ),
        migrations.RemoveField(
            model_name='mediaasset',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='mediaasset',
            name='categories_key',
        ),
        migrations.RemoveField(
            model_name='mediaasset',
            name='created_at',
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['media_type', 'created'], name='video_mason_media_t_0fa926_idx'),
        ),
        migrations.AddField(
            model_name='mediaassetuserstats',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stats', to='video_masonry.mediaasset'),
        ),
        migrations.AddField(
            model_name='mediaassetuserstats',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_asset_stats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mediaassetinteraction',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='video_masonry.mediaasset'),
        ),
        migrations.AddField(
            model_name='mediaassetinteraction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_asset_interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='mediaassetuserstats',
            constraint=models.UniqueConstraint(fields=('user', 'asset'), name='uniq_mediaasset_stats_user_asset'),
        ),
        migrations.AddIndex(
            model_name='mediaassetinteraction',
            index=models.Index(fields=['asset', 'action', 'created'], name='video_mason_asset_i_b62395_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaassetinteraction',
            index=models.Index(fields=['user', 'action', 'created'], name='video_mason_user_id_76b309_idx'),
        ),
    ]
