# Generated by Django 4.2.21 on 2025-09-08 17:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeaDailyUniqueCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('valid_on', models.DateField(verbose_name='valid on')),
                ('kind', models.CharField(choices=[('G', 'General'), ('B', 'Buyer')], default='G', max_length=1, verbose_name='kind')),
                ('code', models.CharField(db_index=True, max_length=64, verbose_name='code')),
                ('sent_to', models.JSONField(blank=True, default=list, verbose_name='sent to emails')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('last_email_message_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='last email message id')),
            ],
            options={
                'verbose_name': 'GEA daily unique code',
                'verbose_name_plural': 'GEA daily unique codes',
                'db_table': 'utils_gea_daily_unique_code',
                'indexes': [models.Index(fields=['valid_on'], name='utils_gea_d_valid_o_b97640_idx'), models.Index(fields=['code'], name='utils_gea_d_code_d5ed3d_idx'), models.Index(fields=['kind', 'valid_on'], name='utils_gea_d_kind_d73791_idx')],
            },
        ),
    ]
