# Generated by Django 4.2.21 on 2025-09-05 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geadailyuniquecode',
            name='kind',
            field=models.CharField(choices=[('G', 'General'), ('B', 'Buyer')], default='G', max_length=1, verbose_name='kind'),
        ),
        migrations.AlterField(
            model_name='geadailyuniquecode',
            name='valid_on',
            field=models.DateField(verbose_name='valid on'),
        ),
        migrations.AddIndex(
            model_name='geadailyuniquecode',
            index=models.Index(fields=['kind', 'valid_on'], name='utils_gea_d_kind_d73791_idx'),
        ),
    ]
