# Generated by Django 4.2.21 on 2025-07-04 23:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProofOfLife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('first_name', models.CharField(max_length=50, verbose_name='Primer nombre')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo nombre (opcional)')),
                ('last_name', models.CharField(max_length=50, verbose_name='Primer apellido')),
                ('second_last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo apellido (opcional)')),
                ('pol_confirmed', models.BooleanField(default=False, verbose_name='Confirmo la prueba de vida (Proof of life, POL)')),
            ],
            options={
                'verbose_name': 'Prueba de vida',
                'verbose_name_plural': 'Pruebas de vida',
                'db_table': 'apps_proof_of_life',
                'ordering': ('-created',),
            },
        ),
    ]
