# Generated by Django 4.2.21 on 2025-07-04 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pol', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProofOfLife',
            new_name='ProofOfLifeModel',
        ),
    ]
