# Generated by Django 4.2.21 on 2025-09-12 00:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCountryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('continent', models.CharField(choices=[('AF', 'Africa'), ('AN', 'Antarctica'), ('AS', 'Asia'), ('CA', 'Central America'), ('EU', 'Europe'), ('NA', 'North America'), ('OC', 'Oceania'), ('SA', 'South America')], default='SA', max_length=3, verbose_name='continent')),
                ('es_country_name', models.CharField(max_length=100, verbose_name='Country Name (ES)')),
                ('en_country_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country Name (EN)')),
            ],
            options={
                'verbose_name': '3. Country',
                'verbose_name_plural': '3. Countries',
                'db_table': 'apps_assets_location_country',
                'ordering': ['default_order', '-created', 'continent'],
            },
        ),
        migrations.CreateModel(
            name='AssetLocationModel',
            fields=[
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('quantity_type', models.CharField(choices=[('U', 'Units'), ('B', 'Boxes')], default='B', max_length=255, verbose_name='quantity type')),
                ('amount', models.PositiveBigIntegerField(verbose_name='amount')),
                ('observations_es', models.TextField(blank=True, null=True, verbose_name='observations (ES)')),
                ('observations_en', models.TextField(blank=True, null=True, verbose_name='observations (EN)')),
            ],
            options={
                'verbose_name': '1. Location Registration',
                'verbose_name_plural': '1. Locations Registration',
                'db_table': 'apps_assets_location_assetlocation',
                'ordering': ['default_order', '-created'],
            },
        ),
        migrations.CreateModel(
            name='LocationModel',
            fields=[
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=150, null=True, verbose_name='location reference')),
                ('description_es', models.TextField(blank=True, null=True, verbose_name='description (ES)')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description (EN)')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assetlocation_location_country', to='assets_location.assetcountrymodel', verbose_name='Country')),
            ],
            options={
                'verbose_name': '2. Location',
                'verbose_name_plural': '2. Locations',
                'db_table': 'apps_assets_location_location',
                'ordering': ['default_order', '-created'],
            },
        ),
    ]
