# Generated by Django 4.2.21 on 2025-09-13 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_initial'),
        ('assets_location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='locationmodel',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assetslocation_location_user', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='assetlocationmodel',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assetlocation_assetlocation_asset', to='assets.assetmodel', verbose_name='Asset'),
        ),
        migrations.AddField(
            model_name='assetlocationmodel',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assetslocation_assetslocation_user', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='assetlocationmodel',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assetlocation_assetlocation_location', to='assets_location.locationmodel', verbose_name='location'),
        ),
        migrations.AlterUniqueTogether(
            name='assetcountrymodel',
            unique_together={('continent', 'es_country_name', 'en_country_name')},
        ),
        migrations.AlterUniqueTogether(
            name='locationmodel',
            unique_together={('reference', 'country', 'created_by', 'is_active', 'description_es', 'description_en')},
        ),
        migrations.AlterUniqueTogether(
            name='assetlocationmodel',
            unique_together={('asset', 'location', 'quantity_type', 'amount', 'created_by')},
        ),
    ]
