# Generated by Django 4.2.21 on 2025-09-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetlocationmodel',
            name='quantity_type',
            field=models.CharField(choices=[('U', 'Units'), ('B', 'Boxes')], default='B', max_length=255, verbose_name='quantity type'),
        ),
    ]
