# Generated by Django 4.2.21 on 2025-09-12 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets_location', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetcountrymodel',
            options={'ordering': ['default_order', '-created', 'continent'], 'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='assetlocationmodel',
            options={'ordering': ['default_order', '-created'], 'verbose_name': 'Location Registration', 'verbose_name_plural': 'Locations Registration'},
        ),
        migrations.AlterModelOptions(
            name='locationmodel',
            options={'ordering': ['default_order', '-created'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
    ]
