# Generated by Django 4.2.21 on 2025-10-20 01:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0002_initial'),
        ('assets_location', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assetlocationmodel',
            unique_together={('asset', 'location', 'quantity_type', 'amount', 'created_by', 'observations_es', 'observations_en')},
        ),
    ]
