# Generated by Django 4.2.7 on 2024-12-28 00:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_assetmodel_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets_location', '0003_remove_assetlocationmodel_observations_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assetlocationmodel',
            unique_together={('asset', 'location', 'quantity_type', 'amount', 'created_by')},
        ),
    ]
